using System.Drawing;
using System.Globalization;

namespace GitUI.Properties
{
    /// <summary>
    /// DESIGNER USAGE INFO!
    ///
    /// This partial class helps to modify the Resources.resx using the designer AND having some custom
    /// code inside the designer generated Resources class.
    /// The only thing to do whenever the Designer is used is to add the partial class modifier in Resources.Designer.cs
    /// which is not generated by the designer code generator.
    ///
    /// As soon as the preprocessor if statements are no longer necessary this class can / should be removed.
    /// </summary>
    public partial class Resources
    {
        public static System.Drawing.Bitmap loadingpanel {
            get {
                if (GitCommands.Utils.EnvUtils.IsMonoRuntime())
                    return loadingpanel_static;
                else
                    return loadingpanel_animated;

            }
        }

        public static System.Drawing.Bitmap IconBlank {
            get {
                return BlankIcon;
            }
        }
    }

    public partial class ResourcesUI
    {
        public static System.Resources.ResourceManager ResourceManager => Resources.ResourceManager;
        public static CultureInfo resourceCulture => Resources.Culture;

        public static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap arrow_refresh_dirty {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh_dirty", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconRepoOpen {
            get {
                object obj = ResourceManager.GetObject("IconRepoOpen", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconBranchCreate {
            get {
                object obj = ResourceManager.GetObject("IconBranchCreate", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap CommitTemplates {
            get {
                object obj = ResourceManager.GetObject("CommitTemplates", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap Icon_50 {
            get {
                object obj = ResourceManager.GetObject("Icon_50", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }


        public static System.Drawing.Bitmap IconAddToGitIgnore {
            get {
                object obj = ResourceManager.GetObject("IconAddToGitIgnore", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconBrowseFileExplorer {
            get {
                object obj = ResourceManager.GetObject("IconBrowseFileExplorer", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }


        public static System.Drawing.Bitmap IconClean {
            get {
                object obj = ResourceManager.GetObject("IconClean", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }



        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCopyToClipboard {
            get {
                object obj = ResourceManager.GetObject("IconCopyToClipboard", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconDiffTool {
            get {
                object obj = ResourceManager.GetObject("IconDiffTool", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconEditFile {
            get {
                object obj = ResourceManager.GetObject("IconEditFile", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconEditGitIgnore {
            get {
                object obj = ResourceManager.GetObject("IconEditGitIgnore", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconFileHistory {
            get {
                object obj = ResourceManager.GetObject("IconFileHistory", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconResetWorkingDirChanges {
            get {
                object obj = ResourceManager.GetObject("IconResetWorkingDirChanges", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconStage {
            get {
                object obj = ResourceManager.GetObject("IconStage", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconStageAll {
            get {
                object obj = ResourceManager.GetObject("IconStageAll", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconUnstage {
            get {
                object obj = ResourceManager.GetObject("IconUnstage", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconUnstageAll {
            get {
                object obj = ResourceManager.GetObject("IconUnstageAll", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap WorkingDirChanges {
            get {
                object obj = ResourceManager.GetObject("WorkingDirChanges", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static Image Icon_77 { get { return null; } }
        public static Image Icon_4 { get { return null; } }

        public static System.Drawing.Bitmap PullFetch {
            get {
                object obj = ResourceManager.GetObject("PullFetch", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap PullRebase {
            get {
                object obj = ResourceManager.GetObject("PullRebase", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap PullFetchAll {
            get {
                object obj = ResourceManager.GetObject("PullFetchAll", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap PullMerge {
            get {
                object obj = ResourceManager.GetObject("PullMerge", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconCommit {
            get {
                object obj = ResourceManager.GetObject("IconCommit", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconFileTree {
            get {
                object obj = ResourceManager.GetObject("IconFileTree", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconDiff {
            get {
                object obj = ResourceManager.GetObject("IconDiff", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconFolderSubmodule {
            get {
                object obj = ResourceManager.GetObject("IconFolderSubmodule", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap Modified {
            get {
                object obj = ResourceManager.GetObject("Modified", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconSubmoduleDirty {
            get {
                object obj = ResourceManager.GetObject("IconSubmoduleDirty", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconFind {
            get {
                object obj = ResourceManager.GetObject("IconFind", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap IconRepoCreate {
            get {
                object obj = ResourceManager.GetObject("IconRepoCreate", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }

        public static System.Drawing.Bitmap RecentRepositories {
            get {
                object obj = ResourceManager.GetObject("RecentRepositories", resourceCulture);
                return obj as System.Drawing.Bitmap;
            }
        }
    }
}
